#!/usr/bin/env python3
"""
format_for_submission.py

Applies submission formatting to MANUSCRIPT.docx for Nephrology Dialysis
Transplantation.

PRESERVES THE AUTHOR'S OWN EDIT. The file submitted to EJHG differed from the
generated MANUSCRIPT.docx in exactly one respect: continuous line numbering
added by hand in Word. That is reapplied here so it is not lost on rebuild.

ALSO FIXES THE DEFECT THAT GOT A SUBMISSION RETURNED. See
flatten_numbered_lists below.

Run AFTER md_to_docx.py. Writes MANUSCRIPT_submission.docx and leaves the
converter output untouched.

Author: Christopher Lawrence
"""

from __future__ import annotations

import copy
import re
from pathlib import Path

from docx import Document
from docx.enum.text import WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt

BODY_FONT = "Times New Roman"   # universally available; Calibri is a Windows default
CODE_FONT = "Courier New"       # Menlo is macOS-only and substitutes unpredictably
BODY_SIZE = Pt(12)

# The author did not double space the EJHG submission. Left off so the file
# matches what was submitted; set True if NDT asks for it.
DOUBLE_SPACE = True

HERE = Path(__file__).resolve().parent
import sys
SRC = HERE / (sys.argv[1] if len(sys.argv)>1 else "MANUSCRIPT.docx")
OUT = HERE / (SRC.stem + "_submission.docx")


def add_line_numbers(section) -> None:
    """Continuous line numbering, restarting at each section."""
    sectPr = section._sectPr
    ln = sectPr.find(qn("w:lnNumType"))
    if ln is None:
        ln = OxmlElement("w:lnNumType")
        sectPr.append(ln)
    ln.set(qn("w:countBy"), "1")
    ln.set(qn("w:start"), "1")
    ln.set(qn("w:restart"), "continuous")


def add_page_numbers(section) -> None:
    """PAGE field centred in the footer."""
    p = section.footer.paragraphs[0] if section.footer.paragraphs \
        else section.footer.add_paragraph()
    p.alignment = 1
    for text, typ in (("begin", "w:fldChar"), ("PAGE", "w:instrText"),
                      ("end", "w:fldChar")):
        r = OxmlElement("w:r")
        el = OxmlElement(typ)
        if typ == "w:fldChar":
            el.set(qn("w:fldCharType"), text)
        else:
            el.set(qn("xml:space"), "preserve")
            el.text = " PAGE "
        r.append(el)
        p._p.append(r)


def strip_non_manuscript(doc) -> int:
    """Delete anything that is not part of the manuscript.

    Two things reach the .docx that must never reach an editor:
      - the HTML draft note at the top of the markdown, which lands as
        paragraph 0 of the Word file and states the submission history;
      - literal "---" horizontal rules, which markdown uses as separators and
        Word renders as three hyphens on their own line.
    Both were present in a file that was one step from being uploaded.
    """
    n = 0
    for para in list(doc.paragraphs):
        txt = para.text.strip()
        if txt.startswith("<!--") or txt.endswith("-->") or \
                re.fullmatch(r"-{3,}|\*{3,}|_{3,}", txt):
            para._element.getparent().remove(para._element)
            n += 1
    return n


def flatten_numbered_lists(doc) -> int:
    """Turn Word auto-numbered list items into literal numbered text.

    THIS IS WHY A SUBMISSION WAS RETURNED. The markdown converter renders the
    reference list as List Number paragraphs, whose numbers are generated by
    Word's numbering engine and do NOT exist as characters in the document
    text. A publisher's technical-check parser extracts "Genovese G, ...
    Science. 2010;329:841-5." with no number in front of it, cannot match the
    in-text "[1]" to it, and reports every reference as uncited. BMC returned
    manuscript 7dbbaf47 on exactly this, ten times over.

    Numbering each entry as literal text costs nothing and removes the class
    of failure entirely.
    """
    n = 0
    counter = 0
    for para in doc.paragraphs:
        if para.style.name != "List Number":
            counter = 0
            continue
        counter += 1
        if para.runs:
            para.runs[0].text = f"{counter}. {para.runs[0].text}"
        else:
            para.add_run(f"{counter}. ")
        para.style = doc.styles["Normal"]
        para.paragraph_format.left_indent = None
        n += 1
    return n


def check_citations(doc) -> list[str]:
    """Refuse to ship a file whose references are not all cited, and vice versa.

    Returns a list of problems. Empty list means the file is internally
    consistent on citation numbering.
    """
    paras = [p.text for p in doc.paragraphs if p.text.strip()]
    try:
        start = next(i for i, t in enumerate(paras)
                     if t.strip().lower() == "references")
    except StopIteration:
        return ["no References heading found"]
    body, refs = paras[:start], []
    for t in paras[start + 1:]:
        m = re.match(r"^(\d+)\.\s+\S", t.strip())
        if m:
            refs.append(int(m.group(1)))
        elif refs:
            break
    cited = []
    for t in body:
        for g in re.findall(r"\[([\d,\s\u2013-]+)\]", t):
            # Expand ranges: "[4-6]" and "[4\u20136]" cite 4, 5 AND 6. Counting only
            # the endpoints reports the middle of every range as uncited, which
            # is a false alarm, not a finding.
            for part in re.split(r"[,\s]+", g.strip()):
                if not part:
                    continue
                m = re.match(r"^(\d+)\s*[-\u2013]\s*(\d+)$", part)
                nums = (range(int(m.group(1)), int(m.group(2)) + 1) if m
                        else [int(x) for x in re.findall(r"\d+", part)])
                for x in nums:
                    if x not in cited:
                        cited.append(x)
    problems = []
    if not refs:
        problems.append("reference list carries no literal numbers "
                        "(auto-numbering will be invisible to the publisher)")
        return problems
    if refs != list(range(1, len(refs) + 1)):
        problems.append(f"reference numbers are not 1..n: {refs}")
    missing = [r for r in refs if r not in cited]
    if missing:
        problems.append(f"references never cited in the text: {missing}")
    dangling = [c for c in cited if c not in refs]
    if dangling:
        problems.append(f"citations with no reference: {dangling}")
    if cited != sorted(cited):
        problems.append(f"citations not in ascending order of first "
                        f"appearance: {cited}")
    return problems


def strip_shading(table) -> None:
    """Remove fills and borders styling; leave a plain grid."""
    table.style = "Table Grid"
    for row in table.rows:
        for cell in row.cells:
            tcPr = cell._tc.get_or_add_tcPr()
            for shd in tcPr.findall(qn("w:shd")):
                tcPr.remove(shd)
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear")
            shd.set(qn("w:fill"), "auto")
            tcPr.append(shd)
            for para in cell.paragraphs:
                for run in para.runs:
                    run.font.color.rgb = None


def repeat_header(table) -> None:
    trPr = table.rows[0]._tr.get_or_add_trPr()
    if trPr.find(qn("w:tblHeader")) is None:
        h = OxmlElement("w:tblHeader")
        h.set(qn("w:val"), "true")
        trPr.append(h)


def strip_thousands(table) -> None:
    """29,989 -> 29989 in table cells only; prose keeps separators."""
    pat = re.compile(r"(?<=\d),(?=\d{3}\b)")
    for row in table.rows:
        for cell in row.cells:
            for para in cell.paragraphs:
                for run in para.runs:
                    if "," in run.text:
                        run.text = pat.sub("", run.text)


def main() -> None:
    doc = Document(SRC)

    # One body font throughout, and one monospace font for code identifiers.
    # The converter emits Menlo for markdown backticks, which exists only on
    # macOS; an editor opening this on Windows would get an arbitrary
    # substitution mid-sentence.
    normal = doc.styles["Normal"]
    normal.font.name = BODY_FONT
    normal.font.size = BODY_SIZE
    rpr = normal.element.get_or_add_rPr()
    rf = rpr.find(qn("w:rFonts"))
    if rf is None:
        rf = OxmlElement("w:rFonts")
        rpr.append(rf)
    for a in ("w:ascii", "w:hAnsi", "w:cs"):
        rf.set(qn(a), BODY_FONT)

    def restyle(runs):
        for run in runs:
            name = run.font.name
            if name is None:
                r = run._r.find(qn("w:rPr"))
                if r is not None:
                    f = r.find(qn("w:rFonts"))
                    if f is not None:
                        name = f.get(qn("w:ascii")) or f.get(qn("w:hAnsi"))
            mono = name in ("Menlo", "Consolas", "Courier", "Monaco",
                            "DejaVu Sans Mono")
            run.font.name = CODE_FONT if mono else BODY_FONT
            run.font.size = BODY_SIZE
            r = run._r.get_or_add_rPr()
            f = r.find(qn("w:rFonts"))
            if f is None:
                f = OxmlElement("w:rFonts")
                r.append(f)
            for a in ("w:ascii", "w:hAnsi", "w:cs"):
                f.set(qn(a), CODE_FONT if mono else BODY_FONT)

    for para in doc.paragraphs:
        pf = para.paragraph_format
        if DOUBLE_SPACE:
            pf.line_spacing_rule = WD_LINE_SPACING.DOUBLE
            pf.space_after = Pt(0)
        restyle(para.runs)

    for section in doc.sections:
        add_line_numbers(section)
        add_page_numbers(section)

    for table in doc.tables:
        strip_shading(table)
        repeat_header(table)
        strip_thousands(table)
        for row in table.rows:
            for cell in row.cells:
                for para in cell.paragraphs:
                    para.paragraph_format.line_spacing_rule = \
                        WD_LINE_SPACING.SINGLE
                    restyle(para.runs)

    # Move the Table 1 caption below the table: the converter emits it above.
    body = doc.element.body
    caps = [p for p in doc.paragraphs
            if p.text.strip().startswith("Table 1.")]
    if caps and doc.tables:
        cap = caps[0]._p
        tbl = doc.tables[0]._tbl
        body.remove(cap)
        tbl.addnext(cap)

    stripped = strip_non_manuscript(doc)
    flat = flatten_numbered_lists(doc)

    problems = check_citations(doc)
    if problems:
        print("\nREFUSING TO WRITE. Citation check failed:")
        for p_ in problems:
            print(f"  - {p_}")
        raise SystemExit(1)

    doc.save(OUT)
    print(f"wrote {OUT.name}")
    print(f"  draft notes and rules removed: {stripped}")
    print(f"  auto-numbered list items made literal: {flat}")
    print("  citation check: every reference cited, numbering 1..n, ascending")
    print(f"  paragraphs: {len(doc.paragraphs)}  double spaced: {DOUBLE_SPACE}")
    print(f"  tables plainified: {len(doc.tables)}")
    print("  line numbers: continuous, page numbers: footer")
    print(f"  fonts: {BODY_FONT} 12pt body, {CODE_FONT} for code identifiers")


if __name__ == "__main__":
    main()
